### ISSUE TITLE
IE 8 in Wine

### ISSUE THREAD

**Issue by sanderd17** [webmonarch/d34raphael#15]
I tried to view the examples like http://webmonarch.github.com/d34raphael/minimal.html in IE 8 via Wine (installed vie PlayOnLinux).

Basic JS code (like printing a "hello world") works in the browser, but the examples don't render.

Is there a difference in the JS engine between IE8 on Windows and IE8 on Linux via Wine?

**Comment by webmonarch** [comment]
As far as I know, there shouldn't be a difference...but, with the complexity of Wine (and IE for that matter), I couldn't say for certain.  Personally, I've found Wine to be more pain than it is worth.  

If you're able, I would suggest VMWare or VirtualBox to run Windows as a virtual machine.

Since it's not obvious this is a d34raphael issue, I'm gonna close the bug for now.

**Comment by sanderd17** [comment]
Thank you, it was indeed a problem with Wine. I see no problems via a virtualised OS.
